---
- hosts: localhost

  ### Load token variable from ini.
  ### do.ini
  ### [default]
  ### do_token=6e.....
  vars:
    do_token: "{{ lookup('ini', 'do_token section=default file=do.ini') }}"

  ###
  ### Tasks
  ###
  tasks:

  # Check user has a valid ssh key.
  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/id_rsa

  # Check key is registered on DigitalOcean
  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=skycloud_ssh_key
      ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: skycloud_ssh_key

  # Create a new droplet with ssh_key.
  - name: ensure `skycloud-droplet` exists
    digital_ocean: >
      state=present
      command=droplet
      name=skycloud-droplet
      unique_name=yes
      size_id=512mb
      region_id=sgp1
      image_id=ubuntu-14-04-x64
      ssh_key_ids={{ skycloud_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: skycloud_droplet

  - debug: msg="IP is {{ skycloud_droplet.droplet.ip_address }}"