--- 
- hosts: dbservers

  vars: 
    - SO_database: exampledb
    - data_archive_directory: /data/data/SO
  tasks: 
    - name: Copy import code to dbservers
      template: src=templates/import.sql dest=/tmp/import.sql

    - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
      mysql_db:
        state: import
        name: "{{SO_database}}"
        target: /tmp/import.sql

#LOAD XML LOCAL INFILE '/pathtofile/file.xml' 
#INTO TABLE my_tablename(personal_number, firstname, ...); 